lvl_match <- function(.f, levels = NULL, model = NULL, ...) {
  if(is.null(levels)) cli::cli_abort("Please provide the levels of the factor.")
  if(is.null(model)) cli::cli_abort("Please provide the chat environment.")

  lvls_unmatched <- setdiff(unique(.f), levels)
  lvls_intersect <- intersect(unique(.f), levels)

  if (model$provider == "ollama") {
    chat <- ellmer::chat_ollama(model = model$model_name)
  } else if (model$provider == "openai") {
    chat <- ellmer::chat_openai(model = model$model_name)
  } else {
    print("Your model is not supported by emend.")
  }

  matched <- lapply(lvls_unmatched, function(x){
    chat$chat(paste0(
      "For '", x, "' (which may be an acronym) return the best match from: ",
      paste(levels, collapse = ", "), ". ",
      "Return 'Unidentified' if no match, not confident or not sure.
      Return result only. No code writing or commentary. ",
      ...
    ))
  })

  out <- unlist(matched)
  out[!out %in% levels] <- "Unidentified"
  dict <- setNames(c(out, lvls_intersect), c(lvls_unmatched, lvls_intersect))
  structure(dict, class = c("lvl_match", class(dict)))
}

messy <- c("US", "U.S.", "USA", "United state", "America", "United Kingdom", "UK", "England")
levels <- c("United States", "United Kingdom")

# This prompt works perfectly
# It ensures every result is independent generated by the LLM
# Because every time it starts a new conversation
matched <- lapply(messy, function(x){
  chat <- ellmer::chat_ollama(model = "llama3.1:8b", seed = 0)
  chat$chat(paste0(
    "For '", x, "', return the best match from the following levels: ",
    paste(levels, collapse = ", "),
    "Return result only. "
  ))
})

# US # United States
chat <- chat_ollama(model = "llama3.1:8b", seed = 0)
chat$chat("For 'US', return the best match from the following levels:
          United States, United Kingdom
          Return result only.")

# USA # United States
chat <- chat_ollama(model = "llama3.1:8b", seed = 0)
chat$chat("For 'USA', return the best match from the following levels:
          United States, United Kingdom
          Return result only.")

# U.S. # United States
chat <- chat_ollama(model = "llama3.1:8b", seed = 0)
chat$chat("For 'U.S.', return the best match from the following levels:
          United States, United Kingdom
          Return result only.")

# America # United States
chat <- chat_ollama(model = "llama3.1:8b", seed = 0)
chat$chat("For 'America', return the best match from the following levels:
          United States, United Kingdom
          Return result only.")

# UK # United Kingdom
chat <- chat_ollama(model = "llama3.1:8b", seed = 0)
chat$chat("For 'UK', return the best match from the following levels:
          United States, United Kingdom
          Return result only.")

# England # United Kingdom
chat <- chat_ollama(model = "llama3.1:8b", seed = 0)
chat$chat("For 'England', return the best match from the following levels:
          United States, United Kingdom
          Return result only.")
